apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    jupyterhub: singleuser-profiles
  name: extra-sizes
data:
  jupyterhub-singleuser-profiles.yaml: |
    sizes:
      - name: Only Limits
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
      - name: Only Requests
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
      - name: Only Memory
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
